In [26]:
import image_dataset
import pandas as pd
import numpy as np
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.nn import functional as F
import torch.nn as nn
import torch

In [2]:
train_dataset = image_dataset.ImageDataset(
    train=True, transform=transforms.ToTensor())

# Wrap in dataloader.
batch_size = 4
train_dl = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)

In [33]:
a = torch.tensor([[-0.2205, -0.1494,  0.0437,  0.0013,  0.0960,  0.1362],
        [-0.1573, -0.2024,  0.0242,  0.0279,  0.1131,  0.1304],
        [-0.1130, -0.2481,  0.0890,  0.0972,  0.0476,  0.0644],
        [-0.1800, -0.1322,  0.1479,  0.0683,  0.0418,  0.1382],
        [-0.1109, -0.3033, -0.0110,  0.0604,  0.1436,  0.1089],
        [-0.1651, -0.1132,  0.2034,  0.0833,  0.0405,  0.1387]])
# nn.Softmax(a)
print(torch.argmax(F.softmax(a, dim=1)))
print(torch.argmax(F.softmax(a, dim=1), dim=1))
# torch.argmax(F.softmax(a), dim=1)
# a1 = a[0]
# print(F.softmax(a1))
# F.softmax(a)[0,:]

tensor(32)
tensor([5, 5, 3, 2, 4, 2])


In [35]:
input1 = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
print(input1)
print(target)
# loss = F.cross_entropy(input1, target)
# loss

tensor([[-0.7131, -2.3878, -0.4756, -0.6871, -0.7291],
        [-0.1910, -0.8900,  1.5842,  2.0730, -0.8305],
        [ 1.1591, -1.1579,  0.1402,  0.0076, -0.4198]], requires_grad=True)
tensor([2, 3, 0])


In [3]:
print(len(train_dl))
for batch in train_dl:
    print(batch[1])

60921
tensor([801, 592, 143, 965])
tensor([929, 736,  99, 316])
tensor([1135,  990,  292,  355])
tensor([445, 175, 884, 171])
tensor([ 757,  787, 1048,  775])
tensor([943, 468, 952, 850])
tensor([994, 666, 369, 753])
tensor([577, 754, 190, 922])
tensor([1117,  746,   33,   10])
tensor([812, 551, 791, 447])
tensor([471, 755, 194, 342])
tensor([ 877,  174,  506, 1003])
tensor([161, 834, 182, 106])
tensor([328, 846, 170, 668])
tensor([  17,  769,  227, 1033])
tensor([704, 171, 990, 590])
tensor([108, 786, 332, 263])
tensor([ 978,  607,  890, 1126])
tensor([456, 419, 436, 620])
tensor([ 493, 1015,  457,  533])
tensor([ 43, 517, 590, 488])
tensor([472, 273, 780, 603])
tensor([ 924,  350, 1014,  571])
tensor([124, 262, 867, 667])
tensor([809, 957, 542,  16])
tensor([943, 593, 188, 744])
tensor([1050,  368,  458,  888])
tensor([1088,  960,  857,  517])
tensor([1136,  789, 1061,   46])
tensor([910, 848, 536, 479])
tensor([209, 248,  30, 810])
tensor([ 780,  293,  340, 1067])
tensor([ 771,  728

KeyboardInterrupt: 